name: Build Assembly Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Crinkler
        run: |
          Invoke-WebRequest -Uri "https://www.crinkler.net/download/crinkler-2-3.zip" -OutFile "crinkler.zip"
          Expand-Archive -Path "crinkler.zip" -DestinationPath "."
          del crinkler.zip
        shell: powershell
      
      - name: Run build.bat
        run: |
          call "C:\Program Files\Microsoft Visual Studio\*\*\VC\Auxiliary\Build\vcvarsall.bat" x86
          build.bat
        shell: cmd
      
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: trpad-executable
          path: trpad.exe
